### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Aspie96** [nejsan/supercollider-music#1]
Hi!

Would you consider licensing this?

This is really interesting because (INAL!) what you've created could be seen both as artwork (music) and as computer code, so the license should be suitable for both.

The following licenses, from the most restrictive to the most permissive, are suitable for both:
- GNU GPL (either version 2 or 3): strong copyleft.
- Permissive licenses including (they are on the same level and in no particular order):
    - Copyfree Open Innovation License (not sure if compatible with the GPL)
    - Open Works License
    - MirOS license (this one might be the best if you pick a license in this category, since it is well known and OSI approved, although it's a bit more software-oriented)
    - GNU All Permissive License (better for single file works thouhgh)
    - Lesser know ones such as:
        - Detachable Public License
        - General Attribution License
- WTFPL
- Creative Commons Zero (not a CC license, but a waiver).

The Creative Commons licenses are not adivsed for software, but they can be used:
- Creative Commons Attribution
- Creative Commons Attribution-ShareAlike 4.0 (copyleft. previous versions are incompatible with the GPL).

Alternatively, you could dual-license this repository under a license for software and a license for creative works such as the Free Art License (copyleft) and any open source license.

**Comment by codehearts** [comment]
I'm a fan of the MIT license, and since I don't touch SuperCollider much these days I'd be happy to see what things people can do with this repo! I'll close this ticket once the license is up
